name: Pull data

on:
    schedule:
        - cron: '5 5 * * 0'		
    workflow_dispatch:

jobs:
    pull-data:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - run: ./pull-data.sh
            
