name: Pull data

on:
    schedule:
        - cron: '5 5 1 * *'
    workflow_dispatch:

jobs:
    pull-data:
        runs-on: ubuntu-latest
        
        steps:
            - run: sudo apt install gdal-bin
            - uses: actions/checkout@main
            - run: ./pull-data.sh
            - run: |-
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git config user.name "Github Actions"
                git add -A Data/
                git commit -m "autopublish: $(date -u +"%Y-%m-%d")"
                git push
